const fs = require('fs');

// Baseline question & upload configuration for all 13 categories
// Note: These category questions and upload requirements are an initial proposed baseline created using
// publicly available industry references, including the TOI Home & Decor Awards structure, and are subject
// to Kutchmitra client review and approval.

const categoriesConfig = [
  {
    code: '01',
    id: 'c2026000-0000-0000-0000-000000000001',
    name: 'Architect of the Year',
    questions: [
      {
        key: 'coa_registration_no',
        text: 'Council of Architecture (COA) / Professional Registration Number',
        help: 'Provide your valid Council of Architecture registration or recognized statutory professional body registration number.',
        placeholder: 'e.g. CA/2015/12345',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        key: 'architectural_concept_statement',
        text: 'Core Architectural Vision & Design Concept',
        help: 'Elaborate on the conceptual design narrative, spatial vision, form generation, and how the architectural solution addresses the client brief.',
        placeholder: 'Describe the overarching architectural narrative, inspiration, and design philosophy...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'spatial_planning_circulation',
        text: 'Spatial Planning, Zoning & Functional Efficiency',
        help: 'Detail how spatial zoning, circulation flow, day-lighting, natural ventilation, and ergonomic utility are optimized in the layout.',
        placeholder: 'Detail spatial zoning, transition between public and private zones, and circulation...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'structural_system',
        text: 'Primary Structural & Construction System',
        help: 'Select the primary structural methodology utilized in this project.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 4,
        options: [
          { label: 'Reinforced Cement Concrete (RCC) Frame', value: 'rcc_frame' },
          { label: 'Load-Bearing Masonry & Arches', value: 'load_bearing_masonry' },
          { label: 'Composite Steel & Concrete Structure', value: 'composite_steel_concrete' },
          { label: 'Hybrid Traditional Timber & Stone Masonry', value: 'hybrid_traditional' },
          { label: 'Prefabricated / Modular Construction', value: 'modular_prefab' },
        ],
      },
      {
        key: 'regional_climate_response',
        text: 'Regional Climate Adaptation & Seismic Sensitivity',
        help: 'Explain how the architectural design specifically addresses Kutch\'s arid climate, thermal comfort, solar path, and Seismic Zone V structural requirements.',
        placeholder: 'Describe passive cooling, shading elements, thermal mass, and seismic considerations...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'indigenous_materials_craft',
        text: 'Indigenous Materials & Traditional Crafts Employed',
        help: 'Select all regional materials and artisan craft disciplines integrated into the architecture.',
        placeholder: null,
        type: 'checkbox',
        required: false,
        order: 6,
        options: [
          { label: 'Local Kutch Yellow Sandstone / Dhrangadhra Stone', value: 'kutch_stone' },
          { label: 'Traditional Lime Plaster & Mortar Finish', value: 'lime_plaster' },
          { label: 'Reclaimed Timber & Local Wood Joinery', value: 'reclaimed_wood' },
          { label: 'Clay Roof Tiles (Kavalu)', value: 'clay_tiles' },
          { label: 'Mud & Mirror Art (Lippan Kaam) Elements', value: 'lippan_art' },
          { label: 'Handcrafted Metal / Jali Craft', value: 'metal_jali' },
        ],
      },
      {
        key: 'video_walkthrough_url',
        text: 'Video Walkthrough / Architectural Presentation Link',
        help: 'Optional URL to an external video walkthrough, drone documentation, or detailed presentation (YouTube, Vimeo, Google Drive).',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 7,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Primary Hero / Cover Photograph',
        description: 'One high-resolution landscape photograph showcasing the definitive architectural view of the project for the jury catalogue.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Completed Architectural Photography',
        description: 'High-resolution exterior and architectural photographs illustrating volumetric form, craftsmanship, and spatial quality (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Architectural Drawings & Layout Plans',
        description: 'Dimensioned floor plans, site plans, key elevations, and cross-sections illustrating spatial zoning and circulation (PDF or High-Res Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Architectural Concept Dossier (PDF)',
        description: 'Comprehensive multi-page presentation covering design philosophy, structural diagrams, and project evolution (Optional, Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '02',
    id: 'c2026000-0000-0000-0000-000000000002',
    name: 'Best Luxury Residence',
    questions: [
      {
        key: 'residence_typology',
        text: 'Residence Typology & Architectural Setting',
        help: 'Specify the physical configuration and estate context of the luxury residence.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 1,
        options: [
          { label: 'Standalone Independent Bungalow', value: 'independent_bungalow' },
          { label: 'Private Gated Estate Home', value: 'gated_estate' },
          { label: 'Farmhouse / Country Retreat', value: 'farmhouse_retreat' },
          { label: 'Luxury Penthouse / Sky Duplex', value: 'luxury_penthouse' },
        ],
      },
      {
        key: 'luxury_design_narrative',
        text: 'Luxury Design Concept & Spatial Grandeur',
        help: 'Describe how the residence embodies luxury through architectural volume, scale, high ceilings, custom detailing, and spatial sequencing.',
        placeholder: 'Describe how luxury is manifested in scale, proportion, light, and materiality...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'indoor_outdoor_integration',
        text: 'Indoor-Outdoor Transition & Landscape Integration',
        help: 'Detail how private courtyards, verandahs (otlas), pergolas, water features, and landscaped outdoor spaces merge with indoor living.',
        placeholder: 'Explain the relationship between the interior rooms and outdoor spaces...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'material_palette_curation',
        text: 'Curated Material Palette & Custom Detailing',
        help: 'Describe the fine materials, imported/indigenous stones, bespoke wood joinery, and specialized finishes that elevate the interior/exterior experience.',
        placeholder: 'Detail the stones, woods, metals, and artisanal finishes specified...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'number_of_bedrooms',
        text: 'Total Number of Bedrooms / Suites',
        help: 'Enter the total count of private bedroom suites in the residence.',
        placeholder: 'e.g. 5',
        type: 'number',
        required: true,
        order: 5,
      },
      {
        key: 'bespoke_amenities',
        text: 'Bespoke Luxury Amenities & Lifestyle Features',
        help: 'Select all dedicated luxury amenities integrated into the residence.',
        placeholder: null,
        type: 'checkbox',
        required: false,
        order: 6,
        options: [
          { label: 'Private Swimming Pool / Plunge Pool', value: 'private_pool' },
          { label: 'Home Cinema / Dolby Atmos Media Lounge', value: 'home_cinema' },
          { label: 'Private Gymnasium / Wellness Spa Room', value: 'wellness_gym' },
          { label: 'Central Landscaped Courtyard with Water Body', value: 'central_courtyard' },
          { label: 'Multi-Car Shaded / Subterranean Garage', value: 'multi_car_garage' },
          { label: 'Staff Quarters & Separate Service Corridors', value: 'service_quarters' },
        ],
      },
      {
        key: 'video_walkthrough_url',
        text: 'Video Walkthrough / Tour Link',
        help: 'Optional link to a video walkthrough or virtual tour of the luxury residence.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 7,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Primary Hero / Cover Photograph',
        description: 'One high-resolution photograph capturing the signature architectural or interior luxury perspective.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Residence Interior & Exterior Photography',
        description: 'Comprehensive photography showing living spaces, master suites, façade, and landscaping (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Floor Plans & Spatial Layout',
        description: 'Dimensioned floor plans showing room dimensions, circulation, and zoning across all levels (PDF or High-Res Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Luxury Residence Dossier (PDF)',
        description: 'Optional PDF presentation detailing material selections, lighting details, and design intent (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '03',
    id: 'c2026000-0000-0000-0000-000000000003',
    name: 'Best Apartment Design',
    questions: [
      {
        key: 'apartment_configuration',
        text: 'Apartment Layout Configuration',
        help: 'Select the unit typology of the nominated apartment.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 1,
        options: [
          { label: '2 BHK Apartment', value: '2bhk' },
          { label: '3 BHK Apartment', value: '3bhk' },
          { label: '4 BHK+ Luxury Apartment', value: '4bhk_plus' },
          { label: 'Duplex / Penthouse Apartment', value: 'penthouse_duplex' },
        ],
      },
      {
        key: 'carpet_area_sqft',
        text: 'Net Carpet Area (Sq. Ft.)',
        help: 'Enter the exact usable carpet area of the apartment in square feet.',
        placeholder: 'e.g. 1850',
        type: 'number',
        required: true,
        order: 2,
      },
      {
        key: 'space_optimization_concept',
        text: 'Space Optimization & Layout Planning Concept',
        help: 'Explain how the layout maximizes usable space, circulation, visual expansiveness, and natural illumination within the apartment footprint.',
        placeholder: 'Describe spatial planning, visual continuity, and open-plan concepts...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'custom_joinery_storage',
        text: 'Custom Joinery & Seamless Storage Solutions',
        help: 'Detail how built-in cabinetry, multifunctional furniture, and concealed storage preserve a clean, uncluttered aesthetic.',
        placeholder: 'Describe custom millwork, concealed utility units, and storage integration...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'lighting_and_material_palette',
        text: 'Lighting Architecture & Material Palette',
        help: 'Detail the artificial lighting design (ambient, task, accent) and the selection of materials, textiles, and surface finishes.',
        placeholder: 'Explain the lighting scheme, ceiling design, and material palette...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'balcony_outdoor_integration',
        text: 'Balcony & Outdoor Extension Design',
        help: 'Describe how the balcony or terrace is designed as a tranquil extension of the living or private quarters.',
        placeholder: 'Describe green walls, seating, flooring, and views...',
        type: 'textarea',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Signature Apartment Hero Photograph',
        description: 'One hero photograph capturing the primary living or dining area showcasing the overall design aesthetic.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Completed Apartment Interior Photographs',
        description: 'High-quality photography of living areas, bedrooms, kitchen, and custom joinery details (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Apartment Furniture Layout & Layout Plan',
        description: 'Dimensioned furniture layout and architectural plan showing space allocation and circulation (PDF or High-Res Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Apartment Design Presentation (PDF)',
        description: 'Optional design deck with material boards, lighting plans, and before/after views if applicable (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '04',
    id: 'c2026000-0000-0000-0000-000000000004',
    name: 'Best Renovation Project',
    questions: [
      {
        key: 'original_structure_age_years',
        text: 'Approximate Age of Structure Prior to Renovation (Years)',
        help: 'Estimated age of the existing building or space before renovation commenced.',
        placeholder: 'e.g. 25',
        type: 'number',
        required: true,
        order: 1,
      },
      {
        key: 'renovation_scope_strategy',
        text: 'Primary Renovation & Intervention Scope',
        help: 'Select the primary classification of the renovation work.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 2,
        options: [
          { label: 'Comprehensive Adaptive Reuse / Structural Overhaul', value: 'adaptive_reuse' },
          { label: 'Complete Interior Transformation & Spatial Re-planning', value: 'interior_transformation' },
          { label: 'Façade Modernization & Exterior Remodeling', value: 'facade_remodel' },
          { label: 'Heritage Restoration with Modern Infrastructure', value: 'heritage_restoration' },
        ],
      },
      {
        key: 'pre_renovation_challenges',
        text: 'Pre-Existing Deficiencies & Project Brief',
        help: 'Describe the structural, spatial, daylighting, or aesthetic limitations of the property prior to the intervention.',
        placeholder: 'Detail structural dampness, poor circulation, low ceiling heights, or outdated services...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'conservation_vs_modernization',
        text: 'Conservation of Existing Elements vs. Modern Additions',
        help: 'Explain which original architectural or structural components were conserved, repaired, or repurposed versus what was newly introduced.',
        placeholder: 'Detail retained masonry, restored woodwork, or newly added structural elements...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'transformation_impact_narrative',
        text: 'Transformation Narrative & User Impact',
        help: 'How has the renovation enhanced liveability, energy efficiency, modern functionality, and longevity for the occupants?',
        placeholder: 'Detail the before-and-after transformation in lifestyle and functionality...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'structural_retrofitting',
        text: 'Structural & Services Retrofitting Upgrades',
        help: 'Select all structural and technical upgrades implemented during the renovation.',
        placeholder: null,
        type: 'checkbox',
        required: false,
        order: 6,
        options: [
          { label: 'Seismic Strengthening / Beam Column Retrofitting', value: 'seismic_retrofit' },
          { label: 'Comprehensive Waterproofing & Damp Proofing Overhaul', value: 'waterproofing' },
          { label: 'Complete Electrical & Smart Rewiring Replacement', value: 'electrical_rewiring' },
          { label: 'Plumbing & Drainage Re-engineering', value: 'plumbing_replacement' },
          { label: 'Thermal Insulation & Energy-Efficient Glazing Upgrade', value: 'thermal_glazing' },
        ],
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Transformed Project Hero Photograph',
        description: 'One hero photograph capturing the renovated space or façade in its completed, transformed state.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Before & After Completed Photography',
        description: 'Comparative photographs demonstrating the pre-renovation condition alongside the finished spaces (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Demolition & Proposed Layout Drawings',
        description: 'Architectural drawings showing the original layout, walls demolished/altered, and the final proposed floor plan (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Renovation Case Study Dossier (PDF)',
        description: 'Optional project dossier documenting on-site challenges, structural solutions, and transformation chronology (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '05',
    id: 'c2026000-0000-0000-0000-000000000005',
    name: 'Best Sustainable Home',
    questions: [
      {
        key: 'passive_solar_strategies',
        text: 'Passive Solar & Bioclimatic Architecture Strategies',
        help: 'Select all passive climatic strategies implemented in the residential design.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 1,
        options: [
          { label: 'Solar Orientation & Optimized Glazing Placement', value: 'solar_orientation' },
          { label: 'Thermal Mass Construction (Rammed Earth, Stone, Cavity Walls)', value: 'thermal_mass' },
          { label: 'Natural Cross-Ventilation & Induced Stack Effect', value: 'cross_ventilation' },
          { label: 'Courtyard Microclimate & Evaporative Cooling Features', value: 'courtyard_cooling' },
          { label: 'Deep Shading Overhangs, Jali Screens & Louvers', value: 'shading_jali' },
          { label: 'Green Roof / High-Albedo Reflective Roof Coating', value: 'cool_roof' },
        ],
      },
      {
        key: 'building_envelope_materials',
        text: 'Eco-Friendly Materials & Embodied Carbon Reduction',
        help: 'Detail the sustainable, non-toxic, locally sourced, and low-embodied-energy materials specified in the home.',
        placeholder: 'Detail mud bricks, fly ash concrete, lime, locally quarried stone, reclaimed timber...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'renewable_energy_system',
        text: 'Renewable Energy Generation & Infrastructure',
        help: 'Select the renewable power configuration operational at the home.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 3,
        options: [
          { label: 'Grid-Connected Rooftop Solar Photovoltaic (PV) System', value: 'solar_grid_tied' },
          { label: 'Hybrid Solar PV System with Battery Storage Backup', value: 'solar_hybrid_battery' },
          { label: 'Solar Water Heating System with Efficient Heat Pump', value: 'solar_water_heating' },
          { label: 'Off-Grid Completely Autonomous Renewable Power', value: 'off_grid_solar' },
          { label: 'Passive Solar Ready (Pre-wired & Infrastructure Enabled)', value: 'solar_ready' },
        ],
      },
      {
        key: 'water_conservation_harvesting',
        text: 'Rainwater Harvesting & Water Management',
        help: 'Detail rainwater storage capacity (tankas), groundwater recharge borewells, greywater recycling, and low-flow plumbing fixtures.',
        placeholder: 'Describe storage capacity in liters, recharge methodology, and water-saving fixtures...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'energy_reduction_percentage',
        text: 'Estimated Grid Energy Reduction (% vs. Conventional Home)',
        help: 'Estimated reduction in monthly electrical consumption achieved through passive design and on-site generation.',
        placeholder: 'e.g. 45',
        type: 'number',
        required: false,
        order: 5,
      },
      {
        key: 'sustainability_certifications',
        text: 'Green Certifications or Third-Party Ratings (If Any)',
        help: 'Mention any IGBC, GRIHA, GEM, or self-monitored energy audit credentials if applicable.',
        placeholder: 'e.g. IGBC Green Homes Platinum or Uncertified Self-Audit',
        type: 'text',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Sustainable Home Hero Photograph',
        description: 'One high-resolution photograph capturing the home\'s bioclimatic form and environmental harmony.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Sustainable Features & Built Photographs',
        description: 'Photographs highlighting passive cooling courtyards, solar arrays, thermal walls, and rainwater systems (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Bioclimatic Sun-Path & Floor Plans',
        description: 'Architectural floor plans with sun-path diagrams, prevailing wind arrows, and ventilation sections (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Sustainability Audit / Presentation (PDF)',
        description: 'Optional technical report outlining energy calculations, water balance sheets, and material sourcing audits (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '06',
    id: 'c2026000-0000-0000-0000-000000000006',
    name: 'Ultra-Luxury Residential Project of the Year',
    questions: [
      {
        key: 'estate_plot_area_sqyd',
        text: 'Total Estate Plot / Land Area (Sq. Yards)',
        help: 'Enter the total land parcel size occupied by the ultra-luxury residential estate.',
        placeholder: 'e.g. 2500',
        type: 'number',
        required: true,
        order: 1,
      },
      {
        key: 'grand_architectural_narrative',
        text: 'Architectural Grandeur & Landmark Identity',
        help: 'Articulate the architectural vision that defines this estate as a benchmark of ultra-luxury, volumetric scale, and timeless aesthetics.',
        placeholder: 'Detail the grand entrance, monumental scale, structural cantilevers, and dramatic volumes...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'craftsmanship_exotic_materials',
        text: 'Master Craftsmanship & Ultra-Premium Materiality',
        help: 'Detail the custom artisanal interventions, book-matched exotic marbles, architectural bronze, specialty woodwork, and high-precision finishes.',
        placeholder: 'Describe rare stones, custom millwork, artisanal ceilings, and luxury materials...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'private_wellness_hospitality',
        text: 'Private Wellness, Hospitality & Entertainment Facilities',
        help: 'Describe the private resort-caliber amenities such as heated infinity pools, spa suites, cigar lounges, private theaters, and chef demonstration kitchens.',
        placeholder: 'Detail dedicated entertainment, spa, and hospitality zones...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'security_automation_infrastructure',
        text: 'High-Level Automation, Security & Privacy Systems',
        help: 'Select the high-end technology and privacy systems integrated across the estate.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 5,
        options: [
          { label: 'Centralized Crestron / KNX Master Automation Protocol', value: 'crestron_knx' },
          { label: 'Multi-Tier Perimeter Security, CCTV & Biometric Entry', value: 'biometric_security' },
          { label: 'Segregated Service Corridors for Complete Family Privacy', value: 'service_corridors' },
          { label: 'Acoustically Isolated Cinema with Professional Dolby Atmos', value: 'dolby_cinema' },
          { label: 'Climate-Controlled Outdoor Living Pavilions', value: 'climate_lounges' },
          { label: 'Centralized Variable Refrigerant Flow (VRF) Air Conditioning', value: 'vrf_ac' },
        ],
      },
      {
        key: 'video_walkthrough_url',
        text: 'Cinematic Video Tour / Drone Footage URL',
        help: 'Optional URL to a high-definition cinematic video walkthrough or drone documentation of the estate.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Ultra-Luxury Hero Exterior / Interior View',
        description: 'One signature high-resolution photograph capturing the landmark grandeur of the estate.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Estate Exterior, Interior & Amenity Photography',
        description: 'Comprehensive high-resolution photographs illustrating grand living spaces, wellness amenities, suites, and night illumination (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Master Site Plan & Architectural Floor Plans',
        description: 'Dimensioned master plan, landscape layout, and detailed floor plans of all levels and service zones (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Ultra-Luxury Project Presentation Dossier (PDF)',
        description: 'Optional complete presentation deck detailing architectural intent, specifications, and custom artisanal works (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '07',
    id: 'c2026000-0000-0000-0000-000000000007',
    name: 'Interior Designer of the Year',
    questions: [
      {
        key: 'interior_design_philosophy',
        text: 'Interior Concept, Aesthetic Vocabulary & Narrative',
        help: 'Describe the overarching design philosophy, conceptual narrative, mood board, and color palette uniting the interior spaces.',
        placeholder: 'Describe the interior aesthetic, atmospheric qualities, and spatial philosophy...',
        type: 'textarea',
        required: true,
        order: 1,
      },
      {
        key: 'primary_interior_style',
        text: 'Primary Interior Design Language',
        help: 'Select the predominant stylistic vocabulary characterizing the project.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 2,
        options: [
          { label: 'Contemporary Minimalist with Warm Materiality', value: 'contemporary_minimalist' },
          { label: 'Modern Indian / Regional Artisanal Fusion', value: 'modern_indian_fusion' },
          { label: 'Classic Elegance & Neo-Classical Detailing', value: 'neo_classical' },
          { label: 'Transitional Chic with Bespoke Millwork', value: 'transitional_chic' },
          { label: 'Raw Industrial & Brutalist Textures', value: 'industrial_raw' },
          { label: 'Biophilic & Earthy Organic Vernacular', value: 'biophilic_organic' },
        ],
      },
      {
        key: 'custom_furniture_curation',
        text: 'Bespoke Furniture Design & Material Execution',
        help: 'Detail the custom furniture pieces designed specifically for this project, including upholstery, timber selection, joinery details, and hardware.',
        placeholder: 'Detail customized seating, tables, cabinetry, and bespoke millwork...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'lighting_design_concept',
        text: 'Layered Architectural & Decorative Lighting Concept',
        help: 'Explain how architectural lighting (recessed, coves, linear accents) interacts with signature decorative fixtures to sculpt interior space and mood.',
        placeholder: 'Detail the lighting scenes, color temperatures, and fixture selection...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'textiles_and_art_integration',
        text: 'Textiles, Soft Furnishings & Fine Art Curation',
        help: 'Describe the selection of fabrics, rugs, window dressings, wall art, sculptures, and accessories that complete the interior atmosphere.',
        placeholder: 'Explain fabric choices, art curation, and decorative styling...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'video_walkthrough_url',
        text: 'Interior Walkthrough Video Link',
        help: 'Optional link to a video tour demonstrating spatial sequencing and lighting dynamics.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Signature Interior Hero Photograph',
        description: 'One high-resolution photograph capturing the quintessential interior viewpoint and design essence.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Completed Interior Photography',
        description: 'High-resolution images of living areas, bedrooms, kitchen, bespoke joinery, and material textures (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Interior Furniture Layout & Reflected Ceiling Plan',
        description: 'Detailed furniture layouts, spatial dimensions, and reflected ceiling / electrical lighting plans (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Interior Design Lookbook & Concept Deck (PDF)',
        description: 'Optional presentation including mood boards, material palettes, 3D visualizations, and custom furniture drawings (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '08',
    id: 'c2026000-0000-0000-0000-000000000008',
    name: 'Emerging Designer',
    questions: [
      {
        key: 'years_of_professional_practice',
        text: 'Years in Independent Professional Practice',
        help: 'State the total number of years your independent studio has been practicing (must be 7 years or fewer for this category).',
        placeholder: 'e.g. 3',
        type: 'number',
        required: true,
        order: 1,
      },
      {
        key: 'foundational_design_ethos',
        text: 'Studio Manifesto & Emerging Design Ethos',
        help: 'What design philosophy, fresh perspective, or distinctive methodologies define your practice as an emerging voice in design?',
        placeholder: 'Describe your design vision, creative drive, and studio methodology...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'breakthrough_project_narrative',
        text: 'Nominated Project Innovation & Creative Breakthrough',
        help: 'Explain what makes this nominated project unique, bold, or experimentally distinctive compared to conventional industry approaches.',
        placeholder: 'Describe the key creative risk taken and the breakthrough result...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'resourcefulness_budget_innovation',
        text: 'Resourcefulness, Material Exploration & Constraints Handled',
        help: 'How did you navigate budget constraints, tight timelines, or technical challenges through creative design and material ingenuity?',
        placeholder: 'Explain clever material repurposing, custom detailing on a budget, or inventive solutions...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'design_disciplines_handled',
        text: 'Design Disciplines Handled In-House for this Project',
        help: 'Select all design phases managed directly by your studio.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 5,
        options: [
          { label: 'Architectural Concept & Form Design', value: 'architecture' },
          { label: 'Interior Space Planning & Decoration', value: 'interior_design' },
          { label: 'Bespoke Furniture & Product Prototyping', value: 'furniture_design' },
          { label: 'Lighting Design & Fixture Customization', value: 'lighting_design' },
          { label: 'Landscape & Courtyard Concept', value: 'landscape_design' },
          { label: 'On-Site Execution Supervision & Styling', value: 'execution_styling' },
        ],
      },
      {
        key: 'future_vision_statement',
        text: 'Aspiration for Regional Design in Kutch & Gujarat',
        help: 'What future contribution or architectural impact do you aspire to make in Kutch and Western India over the next decade?',
        placeholder: 'Share your vision for the future of regional design...',
        type: 'textarea',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Breakthrough Project Hero Photograph',
        description: 'One standout photograph showcasing the design innovation of the nominated project.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Project Photography & Detail Shots',
        description: 'High-resolution images of completed spaces, innovative details, craftsmanship, and styling (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Design Drawings & Concept Sketches',
        description: 'Floor plans, conceptual sketches, or section diagrams illustrating the spatial idea (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Studio Portfolio & Project Profile (PDF)',
        description: 'Optional profile showcasing your studio background, creative journey, and nominated project documentation (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '09',
    id: 'c2026000-0000-0000-0000-000000000009',
    name: 'Best Compact Home',
    questions: [
      {
        key: 'total_carpet_area_sqft',
        text: 'Exact Carpet Area of Compact Residence (Sq. Ft.)',
        help: 'Enter the net usable carpet area (typically under 1,200 sq. ft. for compact home evaluation).',
        placeholder: 'e.g. 780',
        type: 'number',
        required: true,
        order: 1,
      },
      {
        key: 'compact_planning_concept',
        text: 'Micro-Planning & Multi-Functional Space Concept',
        help: 'Explain how every square foot was engineered for optimal efficiency, fluid circulation, and high liveability without feeling cramped.',
        placeholder: 'Detail the open-plan layout, elimination of dead corridors, and dual-purpose zones...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'transformable_furniture_storage',
        text: 'Transformable Furniture & Clever Storage Strategies',
        help: 'Describe multifunctional, fold-away, or custom concealed joinery used to preserve openness and provide generous storage.',
        placeholder: 'Describe fold-down tables, hidden wardrobes, under-bed storage, or modular dividers...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'visual_expansion_techniques',
        text: 'Spatial Illusion & Visual Expansiveness Techniques',
        help: 'Select all visual strategies employed to make the compact home feel significantly larger.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 4,
        options: [
          { label: 'Continuous Seamless Flooring Across Entire Unit', value: 'seamless_flooring' },
          { label: 'Strategic Mirror Placement & Reflective Surfaces', value: 'reflective_mirrors' },
          { label: 'Sliding Pocket Doors & Flush Concealed Doors', value: 'pocket_doors' },
          { label: 'Monochromatic Light Color Palette with Textured Accents', value: 'light_palette' },
          { label: 'Floor-to-Ceiling Vertical Storage Accentuating Height', value: 'vertical_storage' },
          { label: 'Unobstructed Sightlines from Entrance to Windows', value: 'clear_sightlines' },
        ],
      },
      {
        key: 'natural_light_ventilation',
        text: 'Natural Daylighting & Airflow Optimization',
        help: 'Describe how natural daylight penetration and cross-ventilation are maximized within the compact footprint.',
        placeholder: 'Explain window placement, sheer curtains, transom glass, or light wells...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'cost_efficiency_solutions',
        text: 'Cost Efficiency & Durable Material Selections',
        help: 'How were premium design aesthetics balanced with budget mindfulness and high-durability surfaces?',
        placeholder: 'Describe low-maintenance materials, laminates, engineered stones, and budget optimization...',
        type: 'textarea',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Compact Home Hero Photograph',
        description: 'One high-resolution photograph capturing the primary living space demonstrating open spatial flow.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Completed Compact Interior Photographs',
        description: 'High-resolution images showing smart furniture, storage solutions, kitchen, bedroom, and multifunctional areas (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Detailed Dimensioned Furniture Layout',
        description: 'Clear dimensioned layout plan showing furniture placement, storage depths, and circulation clearances (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Compact Design Presentation (PDF)',
        description: 'Optional design presentation illustrating custom storage details, axonometric diagrams, and material specs (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '10',
    id: 'c2026000-0000-0000-0000-000000000010',
    name: 'Best Smart Home',
    questions: [
      {
        key: 'smart_ecosystem_protocol',
        text: 'Primary Automation Protocol & System Architecture',
        help: 'Select the primary automation backbone used in the residence.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 1,
        options: [
          { label: 'KNX / DALI (Hardwired Professional International Standard)', value: 'knx_dali' },
          { label: 'Control4 / Crestron System Ecosystem', value: 'control4_crestron' },
          { label: 'Zigbee 3.0 / Z-Wave Professional Wireless Mesh', value: 'zigbee_zwave' },
          { label: 'Matter / Apple HomeKit Unified IP Ecosystem', value: 'matter_homekit' },
          { label: 'Hybrid Hardwired Bus & Secure Wireless Network', value: 'hybrid_system' },
        ],
      },
      {
        key: 'integrated_subsystems',
        text: 'Integrated Smart Subsystems & Controls',
        help: 'Select all home systems centrally coordinated through the smart platform.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 2,
        options: [
          { label: 'Architectural Lighting Automation & Dimming (DALI / Phase Cut)', value: 'lighting_control' },
          { label: 'Climate & HVAC Automation with Zone Sensors', value: 'hvac_control' },
          { label: 'Motorized Curtains, Blinds & Architectural Louvers', value: 'motorized_shading' },
          { label: 'Multi-Room Audio & Distributed High-Res Video', value: 'multiroom_av' },
          { label: 'Integrated Smart Security, CCTV & Video Door Intercom', value: 'security_surveillance' },
          { label: 'Smart Water Tank Sensors & Automated Irrigation', value: 'irrigation_water' },
          { label: 'Energy Monitoring, Solar Management & Load Balancing', value: 'energy_monitoring' },
        ],
      },
      {
        key: 'user_experience_interface',
        text: 'User Interface, Controls & Multi-Generational Ease of Use',
        help: 'Explain how the home is controlled (physical smart keypads, mobile app, touchscreens, voice) and how easily elderly residents or guests can operate it.',
        placeholder: 'Detail the balance between physical intuitive switches and digital apps...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'scene_automations_logic',
        text: 'Custom Lifestyle Scenes & Predictive Automations',
        help: 'Detail key programmed scenes (e.g., Morning Wakeup, Welcome Home, Movie Night, All-Off Night, Energy-Saving Away) and sensor-driven logic.',
        placeholder: 'Describe customized automations and scheduled routines...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'system_resilience_failsafe',
        text: 'Network Security, Offline Resilience & Failsafes',
        help: 'How does the system ensure local operation during internet outages, network security against intrusion, and physical manual overrides?',
        placeholder: 'Explain local hub processing, firewall protection, and manual switch overrides...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'video_walkthrough_url',
        text: 'Smart Home Automation Video Demo Link',
        help: 'Optional URL showcasing lighting scenes, app control, or motorized automation in live operation.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Smart Home Hero View',
        description: 'One hero photograph capturing an integrated smart living space showing lighting scenes and wall keypad controls.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Smart Features & Hardware Photographs',
        description: 'Photographs of custom wall keypads, rack equipment, motorized curtains, lighting atmospheres, and user touchscreens (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Smart Automation Wiring & Device Placement Plan',
        description: 'Schematic drawings showing device layouts, sensor placements, keypad locations, and distribution board positions (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Smart Home Automation Dossier (PDF)',
        description: 'Optional presentation detailing system architecture, scene specifications, user app screenshots, and hardware bills of quantities (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '11',
    id: 'c2026000-0000-0000-0000-000000000011',
    name: 'Best Themed Project of the Year',
    questions: [
      {
        key: 'thematic_concept_title',
        text: 'Central Theme Title & Conceptual Identity',
        help: 'Provide a concise thematic title defining the design concept (e.g., "Kutchi Vernacular Courtyard Revival", "Jawai Earth Retreat", "Zen Wabi-Sabi Sanctuary").',
        placeholder: 'e.g. Kutchi Vernacular Courtyard Revival',
        type: 'text',
        required: true,
        order: 1,
      },
      {
        key: 'thematic_narrative_inspiration',
        text: 'Thematic Narrative, Historical & Cultural Research',
        help: 'Explain the cultural, historical, geographical, or artistic inspiration behind this themed project.',
        placeholder: 'Describe the cultural backstory, research, and design inspiration...',
        type: 'textarea',
        required: true,
        order: 2,
      },
      {
        key: 'thematic_craftsmanship_motifs',
        text: 'Materialization of Theme through Artisanal Craftsmanship',
        help: 'Detail how the chosen theme is articulated through customized architectural details, carvings, hand-painted murals, specialty plasters, and fabrics.',
        placeholder: 'Describe hand-carved stone, authentic woodwork, jali work, or painted finishes...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'authenticity_vs_modern_utility',
        text: 'Balancing Thematic Authenticity with Modern Comfort',
        help: 'How did you achieve genuine thematic immersion while ensuring contemporary ergonomic comfort, durability, and modern services?',
        placeholder: 'Explain how modern air conditioning, lighting, and plumbing are concealed without breaking character...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'custom_artisanal_collaborations',
        text: 'Artisan Collaborations & Specialized Regional Crafts',
        help: 'Select all traditional craftsmanship disciplines engaged for this thematic project.',
        placeholder: null,
        type: 'checkbox',
        required: false,
        order: 5,
        options: [
          { label: 'Traditional Lippan Kaam (Mud & Mirror Relief Art)', value: 'lippan_kaam' },
          { label: 'Rogan Art / Ajrakh Block-Printed Soft Furnishings', value: 'rogan_ajrakh' },
          { label: 'Hand-Carved Local Yellow Sandstone Jalis & Columns', value: 'hand_carved_stone' },
          { label: 'Traditional Wood Carving & Hand-Turned Lacquered Pillars', value: 'traditional_woodcarving' },
          { label: 'Authentic Terracotta Potteries & Hand-Molded Tiles', value: 'terracotta_craft' },
          { label: 'Hand-Beaten Wrought Iron & Brass Hardware Detailing', value: 'metal_hardware' },
        ],
      },
      {
        key: 'video_walkthrough_url',
        text: 'Themed Project Walkthrough Link',
        help: 'Optional video walkthrough showcasing the immersive atmosphere and artisanal details.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Themed Project Hero Photograph',
        description: 'One high-resolution photograph capturing the quintessential thematic atmosphere and craftsmanship.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Thematic Spaces & Craftsmanship Photography',
        description: 'High-resolution images of themed rooms, artisanal details, custom motifs, and overall spatial composition (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Architectural Plans & Thematic Detail Drawings',
        description: 'Dimensioned floor plans, elevation drawings, or artisan detail sheets illustrating theme execution (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Theme Narrative & Moodbook (PDF)',
        description: 'Optional concept booklet showcasing inspirational references, artisan workshop photos, and material samples (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '12',
    id: 'c2026000-0000-0000-0000-000000000012',
    name: 'Luxury Villa Project of the Year',
    questions: [
      {
        key: 'villa_form_and_levels',
        text: 'Villa Massing & Number of Levels',
        help: 'Specify the volumetric form and vertical zoning of the villa.',
        placeholder: null,
        type: 'select',
        required: true,
        order: 1,
        options: [
          { label: 'Single-Level Sprawling Pavilion Villa', value: 'single_level_pavilion' },
          { label: 'G+1 Two-Storey Contemporary Villa', value: 'g_plus_1' },
          { label: 'G+2 Multi-Level Villa with Private Elevator', value: 'g_plus_2_elevator' },
          { label: 'Split-Level Contoured Landscape Villa', value: 'split_level' },
        ],
      },
      {
        key: 'villa_built_up_area_sqft',
        text: 'Total Built-up Area of Villa (Sq. Ft.)',
        help: 'Enter the total constructed built-up area in square feet.',
        placeholder: 'e.g. 6500',
        type: 'number',
        required: true,
        order: 2,
      },
      {
        key: 'architectural_form_envelope',
        text: 'Architectural Expression, Façade & Volumetric Presence',
        help: 'Detail the villa\'s exterior architectural presence, cantilevered canopies, roofline articulation, and façade materiality.',
        placeholder: 'Describe the volumetric composition, geometry, deep verandahs, and materials...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'landscape_pool_living',
        text: 'Landscape Architecture, Verandahs & Swimming Pool Integration',
        help: 'Describe how the villa embraces outdoor living with landscaped gardens, otla verandahs, swimming pool deck, and shaded courtyards.',
        placeholder: 'Detail pool design, outdoor entertainment cabanas, pergolas, and landscape harmony...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'master_suite_sanctuary',
        text: 'Master Suite Sanctuary & Private Living Quarters',
        help: 'Detail the master wing planning, walk-in dressing suites, luxury ensuite spa bathrooms, and private open-to-sky courts or verandas.',
        placeholder: 'Describe the master bedroom wing, private lounge, and ensuite detailing...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'video_walkthrough_url',
        text: 'Villa Video Tour / Drone Footage URL',
        help: 'Optional URL to a high-definition video walkthrough or drone overview of the villa.',
        placeholder: 'https://...',
        type: 'url',
        required: false,
        order: 6,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Luxury Villa Signature Hero Photograph',
        description: 'One high-resolution landscape photograph showcasing the definitive architectural view of the villa.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Completed Villa Exterior & Interior Photography',
        description: 'Comprehensive high-resolution images of villa façades, living spaces, master suites, pool pavilion, and gardens (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'Villa Master Site Plan & Floor Plans',
        description: 'Dimensioned floor plans, site plan, elevations, and sections showing landscape boundary and spatial flow (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'portfolio_pdf',
        title: 'Villa Architectural Dossier (PDF)',
        description: 'Optional complete presentation document including architectural concept, material specifications, and design drawings (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 4,
      },
    ],
  },

  {
    code: '13',
    id: 'c2026000-0000-0000-0000-000000000013',
    name: 'Best Contractor of the Year',
    questions: [
      {
        key: 'contractor_business_profile',
        text: 'Contracting Firm Profile & Operating Background in Kutch',
        help: 'Overview of your contracting enterprise, years of operation in Kutch/Gujarat, core staff size, and key commercial/residential capabilities.',
        placeholder: 'Summarize your contracting firm background, team capabilities, and regional footprint...',
        type: 'textarea',
        required: true,
        order: 1,
      },
      {
        key: 'turnkey_scope_of_work',
        text: 'Execution Scopes Executed for Nominated Project',
        help: 'Select all technical and construction packages executed by your firm for this nominated project.',
        placeholder: null,
        type: 'checkbox',
        required: true,
        order: 2,
        options: [
          { label: 'Civil & Structural RCC / Masonry Framework', value: 'civil_structural' },
          { label: 'Full Turnkey Execution (Civil + Finishing + MEP)', value: 'full_turnkey' },
          { label: 'High-Precision Interior Fitout, Carpentry & Millwork', value: 'interior_fitout' },
          { label: 'Advanced Structural Waterproofing & Protective Treatments', value: 'waterproofing' },
          { label: 'MEP Infrastructure (Plumbing, Electrical, HVAC, Fire Safety)', value: 'mep_infrastructure' },
          { label: 'Specialized Stone Masonry, Cladding & Exterior Paving', value: 'stone_cladding' },
        ],
      },
      {
        key: 'quality_control_workmanship',
        text: 'Quality Control Standards, Material Testing & Workmanship',
        help: 'Detail your on-site quality assurance processes (concrete cube testing, compaction, line & level checking, raw material verification, mock-ups).',
        placeholder: 'Describe your testing protocols, tolerance standards, and how workmanship precision was verified...',
        type: 'textarea',
        required: true,
        order: 3,
      },
      {
        key: 'coordination_with_architects',
        text: 'Coordination with Architects, Structural Engineers & Clients',
        help: 'Explain how your team translated architectural drawings into physical reality, coordinated structural consultants, managed RFI processes, and resolved detail clashes.',
        placeholder: 'Describe coordination meetings, drawing reviews, and alignment with the design vision...',
        type: 'textarea',
        required: true,
        order: 4,
      },
      {
        key: 'project_delivery_schedule_management',
        text: 'Schedule Management, Milestone Tracking & Material Logistics',
        help: 'Detail how you managed project schedules, labor deployment, supply chain logistics across Kutch, and timely handover.',
        placeholder: 'Explain project scheduling tools, procurement planning, and milestone adherence...',
        type: 'textarea',
        required: true,
        order: 5,
      },
      {
        key: 'site_challenges_problem_solving',
        text: 'Difficult Site Conditions & Technical Problem Solving',
        help: 'Describe a significant technical, geotechnical, weather, or structural challenge encountered on this project and the exact engineering solution executed.',
        placeholder: 'Detail a specific challenge (e.g. soil condition, seismic detailing, material scarcity) and your solution...',
        type: 'textarea',
        required: true,
        order: 6,
      },
      {
        key: 'safety_sustainability_practices',
        text: 'Site Safety Protocols, Labor Welfare & Waste Management',
        help: 'Detail your on-site safety standards, PPE compliance, worker welfare, and responsible construction debris recycling/disposal.',
        placeholder: 'Describe safety measures, labor amenities, zero-accident record, and debris handling...',
        type: 'textarea',
        required: true,
        order: 7,
      },
      {
        key: 'total_project_construction_value',
        text: 'Approximate Contract / Construction Value (Lakhs INR)',
        help: 'Optional: State the approximate construction contract value handled in Lakhs INR.',
        placeholder: 'e.g. 150',
        type: 'number',
        required: false,
        order: 8,
      },
    ],
    uploads: [
      {
        type: 'cover_image',
        title: 'Contractor Nominated Project Hero View',
        description: 'One signature high-resolution photograph showcasing the completed project demonstrating construction excellence.',
        required: true,
        min: 1,
        max: 1,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 1,
      },
      {
        type: 'project_photo',
        title: 'Execution Quality & Completed Site Photography',
        description: 'High-resolution photographs illustrating structural precision, finish quality, masonry, joinery, and completed project handover (Minimum 3 photographs).',
        required: true,
        min: 3,
        max: 10,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp'],
        order: 2,
      },
      {
        type: 'floor_plan',
        title: 'As-Built Drawings / Key Structural Plans',
        description: 'Key architectural or structural drawings illustrating project scale and complexity of execution (PDF or Image).',
        required: true,
        min: 1,
        max: 5,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 3,
      },
      {
        type: 'supporting_doc',
        title: 'Completion Certificate / Architect Recommendation / Work Order',
        description: 'Official proof of project completion such as an architect handover sign-off, client commendation letter, or formal completion certificate (PDF or Image).',
        required: true,
        min: 1,
        max: 3,
        maxSizeMb: 15,
        mime: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
        order: 4,
      },
      {
        type: 'portfolio_pdf',
        title: 'Contractor Company Profile & Project Dossier (PDF)',
        description: 'Optional company brochure detailing past completed projects, plant & machinery capabilities, and client references (Max 15MB).',
        required: false,
        min: 0,
        max: 1,
        maxSizeMb: 15,
        mime: ['application/pdf'],
        order: 5,
      },
    ],
  },
];

module.exports = { categoriesConfig };
